### ISSUE TITLE
Use something else than developer products for donations

### ISSUE THREAD

**Issue by ccuser44** [Cosmental/Social-Chat-V2#6]
Currently Social Chat V2 uses developer products for donations. `MarketplaceService:PromptProductPurchase`

Developer products are only available for the current game. Meaning you can't donate from games outside of the game.

**Comment by Cosmental** [comment]
Oh I didnt realize 😓 

This is a huge problem, what can I use alternatively?

**Comment by ccuser44** [comment]
> Oh I didnt realize 😓
> 
> This is a huge problem, what can I use alternatively?

You can either use game-passes (can only be bought once) or you can use sellable T-Shirts/Shirts (can be only bought once).

**Comment by Cosmental** [comment]
Ah I see! Thank you for your help! :D
